### ISSUE TITLE
c'est quoi GSB-2017-Android?

### ISSUE THREAD

**Issue by pascalfares** [ayounes3333/GSB-2017-Android#1]

**Comment by ayounes3333** [comment]
GSB 2017 Android est un submodule qui représente l'application android de gestion du stock. il a était ajouter pour séparer le projet android du projet principale.

**Comment by elieohanian** [comment]
on est dans le meme team Gestion de Stock Phoenix Team
<https://github.com/ChirazeHaidar/vc/projects/1>
on travail sur la partie android
